export enum SystemErrorCode {
    // ? FORM ERROR
    // ! LOGIN
    LOGIN_FAILED = 1001,
    INVALID_PASSWORD = 1003,
    TOKEN_REQUIRED = 1004,
    INVALID_TOKEN = 1005,
    TOKEN_GENERATE_FAILED = 1006,

    // ! SIGN UP
    SIGN_UP_FAILED = 1010,

    // ? FORM ERROR
    // ! USER
    USER_NOT_FOUND = 3100,
    USER_MOBILE_NUMBER_EXIST = 3101,
    USER_EMAIL_EXIST = 3102,

    // ? SYSTEM ERROR
    PAGE_NOT_FOUND = 5001,

    // ? FATAL ERROR
    GENERAL_ERROR = 10000,
}
